"""Trace the LSD badge artwork from the clean screenshot into SVG path data.

Usage: python3 scripts/trace-logo.py <screenshot.jpeg>
Writes src/components/brand/lsd-letters.ts (letters only) and lsd-badge.ts (letters + ring text).
Needs: numpy, potracer (pip install potracer) and the project's sharp (via node) for the crop.

potracer treats False pixels as foreground, so masks are inverted before tracing.
"""
import json, os, subprocess, sys, numpy as np, potrace

src = sys.argv[1]
tmp = os.environ.get('TMPDIR', '/tmp')
raw = os.path.join(tmp, 'lsd-badge.raw')
W = 2000
# The badge in the Instagram profile screenshot (720x1600): centre (360, 800), radius ~240.
subprocess.run(['node', '-e', f'''
const sharp=require("sharp");
sharp({json.dumps(src)}).extract({{left:120,top:560,width:480,height:480}}).resize({W},{W},{{kernel:"lanczos3"}})
  .greyscale().normalise().sharpen().threshold(140).raw().toBuffer().then((b)=>require("fs").writeFileSync({json.dumps(raw)},b))
'''], check=True)

buf = np.fromfile(raw, dtype=np.uint8).reshape(W, W)
yy, xx = np.mgrid[0:W, 0:W]
rr = np.sqrt((xx - W / 2) ** 2 + (yy - W / 2) ** 2)
# Disc edge: scanning inward from the outside, the first radius where the ring is almost entirely white.
edge = next(r0 for r0 in range(W // 2 - 4, 600, -2) if (buf[(rr >= r0 - 6) & (rr < r0)] > 128).mean() > 0.97)
dark = buf < 128


def trace(mask):
    path = potrace.Bitmap(~mask).trace(turdsize=40, alphamax=1.0, opttolerance=0.2)
    f = lambda v: f"{v:.1f}".rstrip('0').rstrip('.')
    parts = []
    for c in path:
        s = c.start_point
        d = [f"M{f(s.x)} {f(s.y)}"]
        for seg in c:
            if seg.is_corner:
                d.append(f"L{f(seg.c.x)} {f(seg.c.y)}L{f(seg.end_point.x)} {f(seg.end_point.y)}")
            else:
                d.append(f"C{f(seg.c1.x)} {f(seg.c1.y)} {f(seg.c2.x)} {f(seg.c2.y)} {f(seg.end_point.x)} {f(seg.end_point.y)}")
        d.append('Z')
        parts.append(''.join(d))
    return ''.join(parts), len(parts)


header = "// Generated by scripts/trace-logo.py from the LSD badge artwork. Do not hand-edit.\n"

# Letters only: everything inside the plain ring between letters and ring text.
letters = dark & (rr <= 0.62 * edge)
d, n = trace(letters)
ys, xs = np.where(letters)
bbox = [int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())]
with open('src/components/brand/lsd-letters.ts', 'w') as f:
    f.write(header + f"export const LSD_LETTERS_VIEWBOX = '0 0 {W} {W}'\nexport const LSD_LETTERS_BBOX = {json.dumps(bbox)} as const\nexport const LSD_LETTERS_PATH =\n  '{d}'\n")
print('letters curves', n, 'bbox', bbox)

# Full badge: letters and ring text. Coordinates stay in trace space; the transform centres the disc in a 1000 box.
d, n = trace(dark & (rr <= edge - 4))
scale = 1000 / (2 * edge)
tr = f"translate({-(W / 2 - edge) * scale:.2f} {-(W / 2 - edge) * scale:.2f}) scale({scale:.5f})"
with open('src/components/brand/lsd-badge.ts', 'w') as f:
    f.write(header + "// Path coordinates live in the trace space; the transform maps them into a 1000x1000 viewBox centred on the disc.\n"
            f"export const LSD_BADGE_TRANSFORM = '{tr}'\nexport const LSD_BADGE_PATH =\n  '{d}'\n")
print('badge curves', n, 'edge', edge)
