"""Trace the LSD letterforms from a thresholded raw greyscale crop into SVG path data.

Input: a raw 8-bit buffer (1 or 3 channels) of a square crop where the letters are dark
on white. A circular mask drops ring-text fragments in the corners. Output: an SVG file
and a TS module exporting the path string (viewBox 0 0 1000 1000).
"""
import sys, json, numpy as np, potrace

raw, w, h, ch, out_svg, out_ts = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]), sys.argv[5], sys.argv[6]
buf = np.fromfile(raw, dtype=np.uint8).reshape(h, w, ch)[:, :, 0]
yy, xx = np.mgrid[0:h, 0:w]
inside = (xx - w / 2) ** 2 + (yy - h / 2) ** 2 <= (0.47 * w) ** 2
mask = (buf < 128) & inside

bmp = potrace.Bitmap(mask)
path = bmp.trace(turdsize=40, alphamax=1.0, opttolerance=0.2)

def fmt(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")

parts = []
for curve in path:
    s = curve.start_point
    d = [f"M{fmt(s.x)} {fmt(s.y)}"]
    for seg in curve:
        if seg.is_corner:
            c, e = seg.c, seg.end_point
            d.append(f"L{fmt(c.x)} {fmt(c.y)}L{fmt(e.x)} {fmt(e.y)}")
        else:
            c1, c2, e = seg.c1, seg.c2, seg.end_point
            d.append(f"C{fmt(c1.x)} {fmt(c1.y)} {fmt(c2.x)} {fmt(c2.y)} {fmt(e.x)} {fmt(e.y)}")
    d.append("Z")
    parts.append("".join(d))
d_attr = "".join(parts)

# tight bbox so the component can centre the letters
ys, xs = np.where(mask)
bbox = [int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())]

with open(out_svg, "w") as f:
    f.write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}"><path fill="currentColor" fill-rule="evenodd" d="{d_attr}"/></svg>\n')
with open(out_ts, "w") as f:
    f.write("// Generated by scripts/trace-logo.py from the LSD badge artwork. Do not hand-edit.\n")
    f.write(f"export const LSD_LETTERS_VIEWBOX = '0 0 {w} {h}'\n")
    f.write(f"export const LSD_LETTERS_BBOX = {json.dumps(bbox)} as const\n")
    f.write(f"export const LSD_LETTERS_PATH =\n  '{d_attr}'\n")
print("curves", len(parts), "bbox", bbox, "chars", len(d_attr))
